name: Hello_World

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
        pwd
        ls

    - name: clone the git repository
      run: |
        git clone https://github.com/pgunnell/aws-test.git
        ls
        
    - name: change directory and run python script
      run: |
        cd aws-test
        ls
        python hello_world.py
