name: Hello_World

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
        pwd
        ls

    - name: clone the git repository
      run: |
        git clone https://github.com/pgunnell/aws-test.git
        ls
        
    - name: change directory and run python script
      run: |
        cd aws-test
        ls
        python hello_world.py
        
    - name: try to install dependencies
      run: |
        pip install numpy
        pip install pandas
    
    - name: Configure AWS credentials for accessing S3 buckets
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: copy the file to aws s3
      run: |
        cd aws-test
        ls
        aws s3 cp hello_world.py s3://aws-s3-pipeline-test/
        
    # - name: adding tag to used bucket and pipeline (command for reference, only needed once)
    #  run: |
    #    aws s3api put-bucket-tagging --bucket aws-s3-pipeline-test --tagging 'TagSet=[{Key=806,Value=data-science}]'
    #    aws datapipeline add-tags --pipeline-id df-00627471SOVYZEXAMPLE --tags key=environment,value=production key=owner,value=sales
