name: Hello_World

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
        pwd
        ls

    - name: clone the git repository
      run: |
        git clone https://github.com/pgunnell/aws-test.git
        ls
        
    - name: change directory and run python script
      run: |
        cd aws-test
        ls
        python hello_world.py
    
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: copy the file to aws s3
      run: |
        cd aws-test
        ls
        aws s3 cp hello_world.py s3://aws-s3-pipeline-test/
